DATASOURCES = {
    "weekforecast": {
        "url": "http://metservice.intnet.mu",
        "cache_key": "weekforecast",
        "parser": "parse_weekforecast",
        "requires_internet": True,
    },
    "cityforecast": {
        "url": "http://metservice.intnet.mu",
        "cache_key": "cityforecast",
        "parser": "parse_cityforecast",
        "requires_internet": True,
    },
    "main_message": {
        "url": "http://metservice.intnet.mu",
        "cache_key": None,
        "parser": "parse_main_message",
        "requires_internet": True,
    },
    "special_bulletin": {
        "url": "http://metservice.intnet.mu/warning-bulletin-special-weather.php",
        "cache_key": None,
        "parser": "parse_special_bulletin",
        "requires_internet": True,
    },
    "sunrisemu": {
        "url": "http://metservice.intnet.mu/sun-moon-and-tides-sunrise-sunset-mauritius.php",
        "cache_key": "sunrisemu",
        "parser": "parse_sunrise_table",
        "requires_internet": True,
    },
    "sunriserodr": {
        "url": "http://metservice.intnet.mu/sun-moon-and-tides-sunrise-sunset-rodrigues.php",
        "cache_key": "sunriserodr",
        "parser": "parse_sunrise_table",
        "requires_internet": True,
    },
    "moonrisemu": {
        "url": "http://metservice.intnet.mu/sun-moon-and-tides-moonrise-moonset-mauritius.php",
        "cache_key": "moonrisemu",
        "parser": "parse_moonrise_table",
        "requires_internet": True,
    },
    "moonriserodr": {
        "url": "http://metservice.intnet.mu/sun-moon-and-tides-moonrise-moonset-rodrigues.php",
        "cache_key": "moonriserodr",
        "parser": "parse_moonrise_table",
        "requires_internet": True,
    },
    "moonphase": {
        "url": "http://metservice.intnet.mu/sun-moon-and-tides-moon-phase.php",
        "cache_key": None,
        "parser": "parse_moonphase",
        "requires_internet": True,
    },
    "eclipses": {
        "url": "http://metservice.intnet.mu/sun-moon-and-tides-info-eclipses.php",
        "cache_key": "eclipse_html",
        "parser": "parse_eclipses",
        "requires_internet": True,
    },
    "equinoxes": {
        "url": "http://metservice.intnet.mu/sun-moon-and-tides-info-eclipses.php",
        "cache_key": "eclipse_html",
        "parser": "parse_equinoxes",
        "requires_internet": True,
    },
    "solstices": {
        "url": "http://metservice.intnet.mu/sun-moon-and-tides-info-eclipses.php",
        "cache_key": "eclipse_html",
        "parser": "parse_solstices",
        "requires_internet": True,
    },
    "tides": {
        "url": "http://metservice.intnet.mu/sun-moon-and-tides-tides-mauritius.php",
        "cache_key": "tides",
        "parser": "parse_tides",
        "requires_internet": True,
    },
    "uvindex": {
        "url": None,
        "cache_key": "uvindex",
        "parser": "parse_uvindex",
        "requires_internet": True,
    },
    "latest": {
        "url": "http://metservice.intnet.mu/latest-weather-data.php",
        "cache_key": None,
        "parser": "parse_latest",
        "requires_internet": True,
    },
    "rainfall": {
        "url": "http://metservice.intnet.mu/forecast-bulletin-english-mauritius.php",
        "cache_key": "rainfall",
        "parser": "parse_rainfall",
        "requires_internet": True,
    },
    "eclipse_text": {
        "url": "http://metservice.intnet.mu/sun-moon-and-tides-info-eclipses.php",
        "cache_key": None,
        "parser": "parse_eclipse_text",
        "requires_internet": True,
    },
}
